# Generated by Django 5.2.16 on 2026-07-24 14:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Publique'), ('private', 'Privée')], default='private', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_question_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/%Y/%m/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_questions', to=settings.AUTH_USER_MODEL)),
                ('question_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_lists.questionlist')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Exploration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé')], default='in_progress', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('question_count_at_completion', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_explorations', to=settings.AUTH_USER_MODEL)),
                ('question_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explorations', to='question_lists.questionlist')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('contributor', 'Contributeur'), ('administrator', 'Administrateur')], default='contributor', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_collaborations', to=settings.AUTH_USER_MODEL)),
                ('question_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='question_lists.questionlist')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shown_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exploration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_views', to='question_lists.exploration')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='view_history', to='question_lists.question')),
            ],
            options={
                'ordering': ('shown_at',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('question_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='question_lists.questionlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='questionlist',
            index=models.Index(fields=['visibility', 'is_active'], name='question_li_visibil_4baf7e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlist',
            index=models.Index(fields=['owner', 'is_active'], name='question_li_owner_i_905dff_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_list', 'is_active', 'position'], name='question_li_questio_0d0ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='exploration',
            index=models.Index(fields=['user', 'question_list', 'status'], name='question_li_user_id_21957c_idx'),
        ),
        migrations.AddConstraint(
            model_name='exploration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'question_list'), name='unique_active_exploration_per_user_list'),
        ),
        migrations.AddConstraint(
            model_name='collaboration',
            constraint=models.UniqueConstraint(fields=('question_list', 'user'), name='unique_collaborator_per_list'),
        ),
        migrations.AddIndex(
            model_name='questionview',
            index=models.Index(fields=['exploration', 'shown_at'], name='question_li_explora_31e77e_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionview',
            constraint=models.UniqueConstraint(fields=('exploration', 'question'), name='unique_question_per_exploration'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('question_list', 'user'), name='unique_subscription_per_list'),
        ),
    ]
